twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        smtpServerDomain: '%env(SMTP_SERVER_DOMAIN)%'
        googleAnalyticsId: '%env(GOOGLE_ANALYTICS_ID)%'

when@test:
    twig:
        strict_variables: true
